### ISSUE TITLE
The github pages site has some sort of layout issue

### ISSUE THREAD

**Issue by irrationalpie7** [LazyCats-dev/ao3-podfic-posting-helper#26]
The site at https://lazycats.dev/ seems to have some issues on the bottom left, as I'm looking at it on chrome today:
![image](https://user-images.githubusercontent.com/76858438/168405617-b0fb043e-7c2f-4aab-a6e1-9aaa07526579.png)

**Comment by jermowery** [comment]
Caused by the footer being displayed over the layout of the page. This is really a bug in theme itself, but we can fix it by simply not displaying the footer
