### ISSUE TITLE
Consolidate metadata importing for different ratings levels

### ISSUE THREAD

**Issue by irrationalpie7** [LazyCats-dev/ao3-podfic-posting-helper#27]
There's a url parameter that can be added to AO3 links (e.g. https://archiveofourown.org/works/28542726/chapters/69946179?view_adult=true) that I suspect would let us avoid the special-casing around whether works are mature or not when we import metadata from them. I think that would mean less maintenance burden for that specific piece, and would also make refactoring less error-prone if we ever have any ideas for improving that part.

**Comment by jermowery** [comment]
This can be done by constructing a new URL and changing the search params
