### ISSUE TITLE
Add end notes template

### ISSUE THREAD

**Issue by irrationalpie7** [LazyCats-dev/ao3-podfic-posting-helper#28]
A request that came in today from gee_dee:
"My only remaining wish is that I could fill in a template for end notes, but I'm guessing that's not possible? Other than that, THANK YOU SO MUCH bc it really is an incredible time saver!!!"

Thoughts:
Pop-up's getting a little crowded (my laptop screen is so small 😭) so we'd need to think how we present this to people if we decide to add it, and whether we let people pick whether they want notes to be at the beginning or end or offer both, but on the implementation side the template replacement would work similar to the summary

**Comment by jermowery** [comment]
Fixed in v3.2
