### ISSUE TITLE
[Popup]: Work template strips iframe tag

### ISSUE THREAD

**Issue by jdm** [LazyCats-dev/ao3-podfic-posting-helper#34]
The preview complains that `<iframe src="https://archive.org/embed/litany_202209/litany.mp3" height="30" width="500"></iframe>` isn't supported by AO3, but all my podfic works use it.

**Comment by jermowery** [comment]
Aw I see that AO3's documentation on support tags is out of date

**Comment by jermowery** [comment]
Fixed by https://github.com/LazyCats-dev/ao3-podfic-posting-helper/commit/3795b3c31e04e682193a60169c7f6a4b71384b2f

**Comment by jermowery** [comment]
Will deploy this to all stores now, expect it to update in your browser within 24 hours

**Comment by jermowery** [comment]
Except for Edge, which may take up to 7 days because Microsoft is slow
